services:
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: tasktool_pgbouncer
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 20
    ports:
      - "6432:6432"
    depends_on:
      - postgres

  postgres_replica:
    image: postgres:15-alpine
    container_name: tasktool_db_replica
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # local host port mapping for convenience (optional)
    ports:
      - "55432:5432"

  redis:
    image: redis:7-alpine
    container_name: tasktool_cache_override
    restart: unless-stopped
    ports:
      - "56379:6379"
