apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasktool-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasktool-api
  template:
    metadata:
      labels:
        app: tasktool-api
    spec:
      containers:
        - name: api
          image: your-registry/tasktool-api:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
